### ISSUE TITLE
argparse.ArgumentError: argument --database_name/-d: conflicting option string: -d

### ISSUE THREAD

**Issue by thanhleviet** [quadram-institute-bioscience/scagaire#1]
There are two "-d" arguments in scripts/scagaire

```
Traceback (most recent call last):
  File "/opt/conda/bin/scagaire", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/scagaire/scripts/scagaire", line 27, in <module>
    parser.add_argument('--database_name', '-d',  help='Database name from abricate',  choices=['argannot','card','ncbi', 'plasmidfinder', 'resfinder', 'vfdb'], default = 'resfinder', type=str )
  File "/opt/conda/lib/python3.7/argparse.py", line 1367, in add_argument
    return self._add_action(action)
  File "/opt/conda/lib/python3.7/argparse.py", line 1730, in _add_action
    self._optionals._add_action(action)
  File "/opt/conda/lib/python3.7/argparse.py", line 1571, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/opt/conda/lib/python3.7/argparse.py", line 1381, in _add_action
    self._check_conflict(action)
  File "/opt/conda/lib/python3.7/argparse.py", line 1520, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/conda/lib/python3.7/argparse.py", line 1529, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --database_name/-d: conflicting option string: -d
```

**Comment by thanhleviet** [comment]
Closed as it was fixed
